# GitLeaks configuration file for secret detection

[extend]
# Use the default gitleaks configuration as base
useDefault = true

[allowlist]
# Files to ignore completely
paths = [
    ".*test.*\\.py$",
    ".*mock.*\\.py$",
    ".*fixture.*\\.py$",
    ".*example.*\\.py$",
    ".*\\.lock$",
    ".*\\.log$",
    "htmlcov/.*",
    "cache/.*",
    "logs/.*"
]

# Commit SHAs to ignore
commits = []

# Regular expressions to ignore
regexes = [
    # Test/example API keys and tokens
    "test_api_key",
    "example_token",
    "fake_secret",
    "dummy_password",
    "mock_key",
    # Configuration examples
    "your-api-key-here",
    "your-token-here",
    "replace-with-your-key",
    # Common test patterns
    "sk-test_",
    "pk_test_",
    # UUIDs in tests
    "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
]

# Entropy threshold for generic secrets
[rules.generic-api-key]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey)['":\s]*[=:]\s*['"][a-zA-Z0-9]{20,}['"]'''
entropy = 3.5
secretGroup = 2

# Custom rules for this project
[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
keywords = ["sk-"]

[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-[a-zA-Z0-9\-]{95}'''
keywords = ["sk-ant-"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[A-Za-z0-9_]{36}'''
keywords = ["ghp_", "gho_", "ghu_", "ghs_", "ghr_"]

[[rules]]
id = "docker-config"
description = "Docker configuration credentials"
regex = '''(?i)(docker[_-]?config|dockercfg)['":\s]*[=:]\s*['"][^'"]+['"]'''
keywords = ["docker"]

# Ignore certain file patterns for specific rules
[[rules]]
id = "ignore-test-files"
description = "Ignore secrets in test files"
regex = '''.*'''
paths = [
    "tests/.*",
    ".*test.*",
    ".*mock.*"
]
allowlist = {
    description = "Test files",
    regexTarget = "match"
}