# GitLeaks configuration file for secret detection

[extend]
# Use the default gitleaks configuration as base
useDefault = true

# Global allowlists (modern format as of v8.25.0)
[[allowlists]]
description = "Ignore test files and common false positives"
# Files to ignore completely
paths = [
    ".*test.*\\.py$",
    ".*mock.*\\.py$",
    ".*fixture.*\\.py$",
    ".*example.*\\.py$",
    ".*\\.lock$",
    ".*\\.log$",
    "htmlcov/.*",
    "cache/.*",
    "logs/.*",
    "tests/.*",
    ".*test.*",
    ".*mock.*"
]

# Commit SHAs to ignore
commits = []

# Regular expressions to ignore (targets the secret, not the full match)
regexes = [
    # Test/example API keys and tokens
    "test_api_key",
    "example_token",
    "fake_secret",
    "dummy_password",
    "mock_key",
    # Configuration examples
    "your-api-key-here",
    "your-token-here",
    "replace-with-your-key",
    # Common test patterns
    "sk-test_",
    "pk_test_",
    # UUIDs in tests
    "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
]

# Generic API key rule (modern format)
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey)['":\s]*[=:]\s*['"][a-zA-Z0-9]{20,}['"]'''
entropy = 3.5
secretGroup = 2
keywords = ["api", "key", "apikey"]

# Custom rules for this project
[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
keywords = ["sk-", "openai", "api"]

[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-[a-zA-Z0-9\-]{95}'''
keywords = ["sk-ant-", "anthropic", "claude"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[A-Za-z0-9_]{36}'''
keywords = ["ghp_", "gho_", "ghu_", "ghs_", "ghr_", "github", "token"]

[[rules]]
id = "docker-config"
description = "Docker configuration credentials"
regex = '''(?i)(docker[_-]?config|dockercfg)['":\s]*[=:]\s*['"][^'"]+['"]'''
keywords = ["docker", "config", "dockercfg"]

# JWT Token detection (modern pattern)
[[rules]]
id = "jwt-token"
description = "JSON Web Token"
regex = '''eyJ[A-Za-z0-9+/=]+\.eyJ[A-Za-z0-9+/=]+\.[A-Za-z0-9+/=]*'''
keywords = ["eyJ", "jwt", "token", "bearer"]