version: '3.8'

services:
  # Simple Mode API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AI_DOCS_MODE=simple
      - AI_DOCS_ENVIRONMENT=development
      - AI_DOCS_DEBUG=true
      - AI_DOCS_QDRANT__URL=http://qdrant:6333
      - AI_DOCS_CACHE__ENABLE_DRAGONFLY_CACHE=false
      - AI_DOCS_MONITORING__ENABLE_METRICS=false
      - AI_DOCS_OBSERVABILITY__ENABLED=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
    depends_on:
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Qdrant Vector Database (Simple Config)
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__MAX_REQUEST_SIZE_MB=32
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:

networks:
  default:
    driver: bridge