groups:
  - name: ml_app_alerts
    rules:
      # High error rate alert
      - alert: HighSearchErrorRate
        expr: (rate(ml_app_vector_search_requests_total{status="error"}[5m]) / rate(ml_app_vector_search_requests_total[5m])) * 100 > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High search error rate detected"
          description: "Search error rate is {{ $value }}% for collection {{ $labels.collection }}"

      # Slow search response time
      - alert: SlowSearchResponseTime
        expr: histogram_quantile(0.95, rate(ml_app_vector_search_duration_seconds_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow search response time"
          description: "95th percentile search time is {{ $value }}s for collection {{ $labels.collection }}"

      # High embedding costs
      - alert: HighEmbeddingCosts
        expr: increase(ml_app_embedding_cost_total[1h]) > 10
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "High embedding costs detected"
          description: "Embedding costs are ${{ $value }} per hour for {{ $labels.provider }} {{ $labels.model }}"

      # Low cache hit rate
      - alert: LowCacheHitRate
        expr: (rate(ml_app_cache_hits_total[5m]) / (rate(ml_app_cache_hits_total[5m]) + rate(ml_app_cache_misses_total[5m]))) * 100 < 70
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value }}% for {{ $labels.cache_type }} cache"

      # Service unhealthy
      - alert: ServiceUnhealthy
        expr: ml_app_service_health_status == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is unhealthy"
          description: "Service {{ $labels.service }} is reporting unhealthy status"

      # Dependency unhealthy
      - alert: DependencyUnhealthy
        expr: ml_app_dependency_health_status == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Dependency is unhealthy"
          description: "Dependency {{ $labels.dependency }} is reporting unhealthy status"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (ml_app_system_memory_usage_bytes / 1024 / 1024 / 1024) > 8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "System memory usage is {{ $value }}GB"

      # High CPU usage
      - alert: HighCPUUsage
        expr: ml_app_system_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "System CPU usage is {{ $value }}%"

      # Qdrant collection size growing rapidly
      - alert: QdrantCollectionGrowthRate
        expr: rate(ml_app_qdrant_collection_size[1h]) > 10000
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Rapid Qdrant collection growth"
          description: "Collection {{ $labels.collection }} is growing at {{ $value }} vectors per hour"

      # Task queue backing up
      - alert: TaskQueueBackup
        expr: ml_app_task_queue_size{status="pending"} > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Task queue backing up"
          description: "{{ $labels.queue }} has {{ $value }} pending tasks"