global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ml-app.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'
        send_resolved: true

  # Example email configuration (uncomment and configure as needed)
  # - name: 'email'
  #   email_configs:
  #     - to: 'admin@example.com'
  #       subject: '[ML App] Alert: {{ .GroupLabels.alertname }}'
  #       body: |
  #         {{ range .Alerts }}
  #         Alert: {{ .Annotations.summary }}
  #         Description: {{ .Annotations.description }}
  #         {{ end }}

  # Example Slack configuration (uncomment and configure as needed)
  # - name: 'slack'
  #   slack_configs:
  #     - api_url: 'YOUR_SLACK_WEBHOOK_URL'
  #       channel: '#alerts'
  #       title: 'ML App Alert'
  #       text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']