apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-docs-system

resources:
  - namespace.yaml
  - qdrant-statefulset.yaml
  - dragonfly-deployment.yaml
  - app-deployment.yaml
  - worker-deployment.yaml

configurations:
  - kustomizeconfig/envfrom-references.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: ai-docs-vector-db
  app.kubernetes.io/part-of: ai-docs-system
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  documentation: "https://github.com/your-org/ai-docs-vector-db-hybrid-scraper"
  support-contact: "your-team@company.com"

# Image transformations (replace with your registry)
images:
  - name: ai-docs-app
    newName: your-registry.com/ai-docs-app
    newTag: "v1.0.0"
  - name: ai-docs-worker
    newName: your-registry.com/ai-docs-worker
    newTag: "v1.0.0"

# Resource patches for different environments
patches:
  - path: patches/production-resources.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ai-docs-app
  - path: patches/production-resources.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ai-docs-worker
  - path: patches/production-resources.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: qdrant
  - path: patches/production-resources.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: dragonfly

# Config map generator for application configuration
configMapGenerator:
  - name: ai-docs-config
    literals:
      - AI_DOCS_ENVIRONMENT=production
      - AI_DOCS_DEBUG=false
      - AI_DOCS_LOG_LEVEL=INFO
      - AI_DOCS_MODE=simple
      - AI_DOCS_CACHE__REDIS_URL=redis://dragonfly:6379
      - AI_DOCS_QDRANT__URL=http://qdrant:6333
      - AI_DOCS_QDRANT__COLLECTION_NAME=ai_docs

secretGenerator:
  - name: ai-docs-secrets
    files:
      - secrets/AI_DOCS_OPENAI__API_KEY

