blank_issues_enabled: false
contact_links:
  - name: Questions about repository usage
    url: https://github.com/BjornMelin/ai-docs-vector-db-hybrid-scraper/discussions
    about: Use discussions for open-ended questions or support.
