site_name: AI Docs Vector DB Hybrid Scraper
site_description: A hybrid AI documentation scraping system with vector database integration
site_author: BjornMelin
site_url: https://bjornmelin.github.io/ai-docs-vector-db-hybrid-scraper/

repo_name: BjornMelin/ai-docs-vector-db-hybrid-scraper
repo_url: https://github.com/BjornMelin/ai-docs-vector-db-hybrid-scraper
edit_uri: blob/main/docs/

docs_dir: ../
site_dir: ../../site

copyright: Copyright &copy; 2025 BjornMelin

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: users/quick-start.md
      - Configuration Basics: users/configuration-management.md
      - Examples & Recipes: users/examples-and-recipes.md
      - Search & Retrieval: users/search-and-retrieval.md
      - Troubleshooting: users/troubleshooting.md
  - Architecture & API:
      - Developer Hub: developers/index.md
      - Developer Setup: developers/getting-started.md
      - System Architecture: developers/architecture.md
      - Configuration Reference: developers/configuration.md
      - Service Adapters: developers/service_adapters.md
      - API Reference: developers/api-reference.md
      - App Profiles: developers/app-profiles.md
      - CI/CD Workflows: developers/ci-cd.md
      - Deployment Guide: developers/deployment.md
      - GPU Acceleration: developers/gpu-acceleration.md
      - GitHub Actions: developers/github-actions.md
  - Operations:
      - Operator Hub: operators/index.md
      - Deployment: operators/deployment.md
      - Configuration: operators/configuration.md
      - Monitoring: operators/monitoring.md
      - Operations Runbook: operators/operations.md
      - Release Notes: operators/release-notes.md
      - Service Feedback Monitoring: operators/service_feedback_monitoring.md
  - Security:
      - Overview: security/index.md
      - Security Essentials: security/security-essentials.md
      - Security Checklist: security/security-checklist.md
  - Testing & Observability:
      - Testing Overview: testing/index.md
      - Testing Guide: testing/testing-guide.md
      - MCP Unit Tests: testing/mcp-unit-tests.md
      - Query Processing Metrics: observability/query_processing_metrics.md
      - Evaluation Harness Playbook: testing/evaluation-harness.md
  - Governance:
      - Community Guidelines: contributing/community-guidelines.md
      - Contributor Guide: developers/contributing.md
      - Documentation Metadata: developers/document-metadata.md
      - Technical Debt Log: TECH_DEBT.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BjornMelin/ai-docs-vector-db-hybrid-scraper

strict: true
