name: Documentation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Validate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Python environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: "3.12"
          cache-suffix: "-docs"
          install-dev: 'false'

      - name: Install documentation dependencies
        run: uv sync --frozen --group docs

      - name: Run documentation checks
        run: uv run python scripts/dev.py validate --check-docs --strict

      - name: Build MkDocs site
        run: uv run mkdocs build --strict
