name: Documentation Checks

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: '3.12'
          cache-suffix: '-docs'
          install-dev: false

      - name: Install documentation dependencies
        run: |
          uv sync --frozen --group docs

      - name: Validate documentation links
        run: uv run python scripts/dev.py validate --check-docs --strict

      - name: Build MkDocs site
        run: uv run mkdocs build --strict

      - name: Upload site artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: docs-site
          path: site/
          retention-days: 7
