name: Documentation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Validate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepare workspace
        uses: ./.github/actions/checkout-and-setup
        with:
          python-version: "3.12"
          cache-suffix: "-docs"
          install-dev: 'false'

      - name: Install uv if missing
        run: |
          if ! command -v uv >/dev/null 2>&1; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            export PATH="$HOME/.local/bin:$PATH"
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi

      - name: Ensure uv is available
        run: uv --version

      - name: Install documentation dependencies
        run: uv sync --frozen --extra docs

      - name: Install pytest dependency
        run: uv pip install 'pytest>=8.4.2,<9.0.0'

      - name: Run documentation checks
        run: uv run python scripts/dev.py validate --check-docs --strict

      - name: Build MkDocs site
        run: uv run mkdocs build --strict
