name: Embeddings Unit (PR Fast)

on:
  pull_request:
    paths:
      - 'src/services/embeddings/**'
      - 'tests/unit/services/embeddings/**'
      - 'pytest.ini'
      - 'pyproject.toml'
      - 'uv.lock'

permissions:
  contents: read

jobs:
  embeddings-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup
        uses: ./.github/actions/checkout-and-setup
        with:
          python-version: '3.12'
          cache-suffix: '-embeddings'
      - name: Run embeddings unit tests
        run: |
          uv run pytest --maxfail=1 -q tests/unit/services/embeddings
      - name: Coverage (embeddings)
        run: |
          uv run pytest --cov=src/services/embeddings --cov-report=term-missing -q tests/unit/services/embeddings
