name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true
      
      - name: Install dependencies
        run: uv sync --dev --frozen
      
      - name: Run quick checks
        run: |
          echo "🔍 Running quick validation checks..."
          
          # Check for merge conflicts
          if grep -r "<<<<<<< HEAD" --exclude-dir=.git .; then
            echo "❌ Merge conflicts detected"
            exit 1
          fi
          
          # Validate Python syntax
          uv run python -m py_compile src/**/*.py
          
          # Quick lint check
          uv run ruff check . --select=E9,F63,F7,F82
          
          echo "✅ Quick checks passed"
      
      - name: Comment PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions;
            const deletions = pr.deletions;
            const total = additions + deletions;
            
            let sizeLabel = '🟢 Small';
            if (total > 1000) sizeLabel = '🔴 Large';
            else if (total > 500) sizeLabel = '🟡 Medium';
            
            const comment = `## PR Size Analysis
            
            ${sizeLabel} **Total changes:** ${total} lines
            - ➕ Additions: ${additions}
            - ➖ Deletions: ${deletions}
            
            ${total > 500 ? '⚠️ Consider breaking this PR into smaller chunks for easier review.' : '✅ Good PR size for review.'}`;
            
            github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });