name: Extended Tests (On-Demand)

on:
  workflow_dispatch:
    inputs:
      run_full_tests:
        description: 'Run full pytest suite'
        required: false
        default: 'true'
      run_benchmarks:
        description: 'Run benchmark suite'
        required: false
        default: 'false'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/regression-opt-in.yml'

permissions:
  contents: read

concurrency:
  group: regression-${{ github.ref }}
  cancel-in-progress: true

jobs:
  full-suite:
    name: Full Test Suite
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_full_tests == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: '3.12'
          cache-suffix: '-full-tests'

      - name: Ensure uv is available
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv==0.2.37

      - name: Prepare directories
        run: |
          mkdir -p tests/fixtures/{cache,data,logs}
          mkdir -p logs cache data

      - name: Run full pytest suite
        run: uv run python scripts/dev.py test --profile full --workers 0 --coverage --verbose
        env:
          PYTEST_ADDOPTS: --disable-plugin pytest_benchmark

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: regression-coverage
          path: coverage.xml
          if-no-files-found: ignore
          retention-days: 7

  benchmarks:
    name: Benchmark Suite
    runs-on: ubuntu-latest
    needs: full-suite
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_benchmarks == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: '3.12'
          cache-suffix: '-benchmarks'

      - name: Ensure uv is available
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv==0.2.37

      - name: Install benchmark extras
        run: uv pip install pytest-benchmark

      - name: Run benchmark suite
        run: uv run python scripts/dev.py benchmark --suite all --workers 0

      - name: Upload benchmark results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: benchmark-results
          path: tests/benchmarks
          if-no-files-found: ignore
          retention-days: 7
