name: Issue Triage (Manual)

on:
  workflow_dispatch:
    inputs:
      days_until_stale:
        description: 'Days before marking stale'
        required: false
        default: '30'
      dry_run:
        description: 'Only report, do not label'
        required: false
        default: 'true'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Display suggested triage command
        run: |
          echo "Run triage locally or trigger renovate/stale bots manually as needed."
